//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace real_wf.serviceWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="serviceWCF.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkConnection", ReplyAction="http://tempuri.org/IService1/checkConnectionResponse")]
        int checkConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/uploadFilesToService", ReplyAction="http://tempuri.org/IService1/uploadFilesToServiceResponse")]
        int uploadFilesToService(string Name, string IP, string fileName, string filePath, long fileSize, string fileHash, string udpPort);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Welcome", ReplyAction="http://tempuri.org/IService1/WelcomeResponse")]
        string Welcome(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/connect", ReplyAction="http://tempuri.org/IService1/connectResponse")]
        int connect(string Name, string IP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getData", ReplyAction="http://tempuri.org/IService1/getDataResponse")]
        System.Data.DataTable getData(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/clearUserFiles", ReplyAction="http://tempuri.org/IService1/clearUserFilesResponse")]
        int clearUserFiles(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkUsername", ReplyAction="http://tempuri.org/IService1/checkUsernameResponse")]
        int checkUsername(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchFiles", ReplyAction="http://tempuri.org/IService1/searchFilesResponse")]
        System.Data.DataTable searchFiles(string text, string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : real_wf.serviceWCF.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<real_wf.serviceWCF.IService1>, real_wf.serviceWCF.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int checkConnection() {
            return base.Channel.checkConnection();
        }
        
        public int uploadFilesToService(string Name, string IP, string fileName, string filePath, long fileSize, string fileHash, string udpPort) {
            return base.Channel.uploadFilesToService(Name, IP, fileName, filePath, fileSize, fileHash, udpPort);
        }
        
        public string Welcome(string Name) {
            return base.Channel.Welcome(Name);
        }
        
        public int connect(string Name, string IP) {
            return base.Channel.connect(Name, IP);
        }
        
        public System.Data.DataTable getData(string Name) {
            return base.Channel.getData(Name);
        }
        
        public int clearUserFiles(string name) {
            return base.Channel.clearUserFiles(name);
        }
        
        public int checkUsername(string name) {
            return base.Channel.checkUsername(name);
        }
        
        public System.Data.DataTable searchFiles(string text, string name) {
            return base.Channel.searchFiles(text, name);
        }
    }
}
